apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orchy-worker.fullname" . }}
  labels:
    {{- include "orchy-worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "orchy-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "orchy-worker.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: ORCHY_HOST
            value: "{{ .Values.orchy.host }}"
          - name: ORCHY_PORT
            value: "{{ .Values.orchy.port }}"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
            readinessProbe:
              httpGet:
                path: /actuator/health/readiness
                port: 8081
              initialDelaySeconds: 3
              periodSeconds: 3
